# Generated by Django 4.2.5 on 2023-12-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_digital_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
